Simplify dob backup workflow
metakgp/dob pull request #7
Opened 2024-08-06 14:22 UTC by shikharish

2024-08-06 14:22 UTC, shikharish commented
cc: @rajivharlalka @proffapt

2024-08-08 16:51 UTC, rajivharlalka submitted a review, later dismissed

2024-08-08 16:51 UTC, rajivharlalka commented on backup/run_backup.sh
> +echo -e "\n-- Backup and Rotation finisned at `date +"%Y/%m/%d %H:%M:%S"` --\n"
```suggestion
echo -e "\n-- Backup and Rotation finished at `date +"%Y/%m/%d %H:%M:%S"` --\n"
```

2024-08-11 09:37 UTC, proffapt commented
I will review it tomorrow, ping me once tomorrow. Thanks.

2024-08-13 13:10 UTC, proffapt requested changes
- [ ] remove crontab file
- [ ] container name = image name = metakgporg/dob

2024-08-13 13:10 UTC, proffapt commented on Dockerfile
> +RUN pip3 install -qr ./backup/requirements.txt --break-system-packages
```suggestion
WORKDIR /backup

COPY ./backup .

RUN pip3 install -qr requirements.txt --break-system-packages
```

2024-08-13 13:10 UTC, proffapt commented on docker-compose.yml
> +          "/root/backup/run_backup.sh >> /var/log/backups.log 2>&1 || exit 1",
```suggestion
          "/root/backup/run_backup.sh >> /var/log/pg_dump.log 2>&1 || exit 1",
```

2024-08-13 13:10 UTC, proffapt commented on docker-compose.yml
> +      timeout: 30s
```suggestion
      timeout: 120s
```

2024-08-13 13:27 UTC, proffapt approved these changes

2024-08-13 13:27 UTC, merged